### ISSUE TITLE
Podcast website seems to be offline?

### ISSUE THREAD

**Issue by manu-cyber** [themanifest/transcriptions#6]
I don’t have twitter and couldn’t find an email address on your page Andrew, so this is the only way for me to contact you ;)
It seems the website for the podast is down[0]. Is this an accident or intentional? It would be a shame if your podcast would disappear without properly archiving it first :)
Cheers!

[0] https://downforeveryoneorjustme.com/manifest.fm?proto=https

**Comment by andrew** [comment]
oh weird, looks like something changed on cloudflare or fireside.fm, will try to get it fixed

**Comment by andrew** [comment]
Opened a support ticket with the podcast host, worst case scenario is that I have to move my dns somewhere else but I'll wait to here back.

**Comment by andrew** [comment]
Until it's fixed you can access the podcast here: https://themanifest.fireside.fm/

**Comment by manu-cyber** [comment]
Thank you for addressing this so quickly :) I’m glad this wasn’t by intention and the episodes are not lost.

**Comment by andrew** [comment]
This should be fixed now
